charts/verdaccio/Chart.yaml, charts/verdaccio/values.yaml
This is the last release of v3, actually 3.11.6 is insecure and should not be used anymore.
https://github.com/verdaccio/verdaccio/releases/tag/v3.12.0
=> feat: update docker to v3.12.0

README.md, charts/verdaccio/Chart.yaml, charts/verdaccio/templates/deployment.yaml, charts/verdaccio/templates/service-account.yaml, charts/verdaccio/values.yaml
migration of: https://github.com/helm/charts/pull/21664
Adding serviceAccount as an option, because I am trying to use secrets via vault and without serviceAccount it was impossible
I need to place uplinks with auth-property in the settings of verdaccio and this secret is protected by vault (DOC:  https://verdaccio.org/docs/en/uplinks#auth-property)
=> Adding service-account as optional

charts/verdaccio/Chart.yaml, charts/verdaccio/templates/deployment.yaml, charts/verdaccio/values.yaml
Re-add the feature from https://github.com/helm/charts/pull/20223
For some reason it's included in the README, but appears it got lost somewhere.
=> Add extraEnvVars setting

README.md, charts/verdaccio/Chart.yaml, charts/verdaccio/values.yaml
Updated the version of the default image for the chart to the most recent.
I did the tests and it seems to be very compatible with previous versions, I had no impact, in my case I migrated a chart that was using `3.12.0` to `4.6.2` and everything continued to work perfectly.
I think it is worth keeping the default image on the chart always the most recent, so new people who are going to use the chart will already test the current version.
=> Updated the default image version

charts/verdaccio/Chart.yaml, charts/verdaccio/templates/ingress.yaml, charts/verdaccio/values.yaml
I present this as a suggestion, and it will:
- Update the ingress to remove the second path that conflicts in Traefik 2.x and I assume other ingress controllers that are more strict about their matching.
- Update the deprecated apiVersion for this K8s object and leave an option for backwards compatibility for those that are on older kubernetes versions.
I am running this in production currently and it seems to work with the second ingress path disabled and the new api version.  I have added comments to the values file for posterity.
Would you like anything changed on this?
=> Update Ingress Template

charts/verdaccio/Chart.yaml, charts/verdaccio/values.yaml
The dockerfile has a user for 10001, and the security context was using the wrong one.  So migrating files from the old deployment I had was still stuck with the 10001 uid and lots of things were broken.  This fixes that.
=> Fix UID of deployment to match dockerfile

charts/verdaccio/Chart.yaml, charts/verdaccio/templates/_helpers.tpl, charts/verdaccio/templates/deployment.yaml, charts/verdaccio/templates/service-account.yaml, charts/verdaccio/values.yaml
This PR fixes assignment of a ServiceAccount to the Deployment + adds the option to provide ServiceAccount annotations (eg for using with EKS IRSA).
=> fix: service account and allow setting annotations

README.md
Current Helm(v3) is no longer support `--name` flag, the release name is now mandatory as part of the command. So if you using the `helm install` command in README, you'll get an error like `Error: unknown flag: --name`.
So I edited some examples in README.md
Related links:
* [kubernetes - Helm install unknown flag --name - Stack Overflow](https://stackoverflow.com/questions/57961162/helm-install-unknown-flag-name)
* [Helm | Helm Install](https://helm.sh/docs/helm/helm_install/)
=> Remove name flag from `helm install` command for helm v3

charts/verdaccio/Chart.yaml, charts/verdaccio/templates/ingress.yaml, charts/verdaccio/values.yaml
Closes https://github.com/verdaccio/charts/issues/39. 
Added new variable `.Values.ingress.extraPaths`. This enables  to have path with custom `serviceName` and `servicePort`. 
Something like this can be defined in ingress
```yaml
extraPaths:
- service: ssl-redirect
port: use-annotation
path: /*
```
=> Add support for AWS LoadBalancer Controller with actions annotation

.github/workflows/lint-test.yaml, charts/verdaccio/Chart.yaml, charts/verdaccio/values.yaml, ct.yaml
This PR inlcudes the following GutHub actions for lining the chart:
Here the official example:
https://github.com/helm/charts-repo-actions-demo
https://github.com/helm/chart-testing-action
https://github.com/helm/kind-action
What does it lint?
* correct bump up (verify against the latest changes in chart repository)
* validate yaml
* trigger a local kubernetes to install the chart
=> chore: add linting step

charts/verdaccio/Chart.yaml, charts/verdaccio/values.yaml
Improves considerably the performance of verdaccio using keepAlive  by default
follow up of https://github.com/verdaccio/verdaccio/pull/2014
=> feat: enable keep alive by default

README.md, charts/verdaccio/Chart.yaml
This chart should be based on Helm v3 thus the apiVersion should be `v2`
https://helm.sh/docs/topics/v2_v3_migration/
=> feat!: chart as apiVersion 2

README.md, charts/verdaccio/Chart.yaml, charts/verdaccio/templates/_helpers.tpl, charts/verdaccio/templates/deployment.yaml, charts/verdaccio/templates/service-account.yaml, charts/verdaccio/values.yaml
Setting service account name with `serviceAccount.create` is useful with aws-cdk's service account using IRSA
```typescript
// create service account in cdk kubernetes manifest
const sa = new eks.ServiceAccount(scope, 'verdaccio-sa', {
cluster: ...,
name: 'verdaccio',
});
...
new eks.HelmChart(scope, 'verdaccio', {
...
values: {
serviceAccount: {
enabled: false,  // do not create service account in helm chart
name: sa.serviceAccountName,
}
}
}
```
=> Use create for serviceAccount instead of enabled

README.md, charts/verdaccio/Chart.yaml, charts/verdaccio/templates/NOTES.txt, charts/verdaccio/templates/_helpers.tpl, charts/verdaccio/templates/configmap.yaml, charts/verdaccio/templates/deployment.yaml, charts/verdaccio/templates/ingress.yaml, charts/verdaccio/templates/pvc.yaml, charts/verdaccio/templates/service-account.yaml, charts/verdaccio/templates/service.yaml, charts/verdaccio/values.yaml
We're using this chart internally as an NPM Registry and we were doing some refactoring on it and I figured that some of the changes we made might be useful to you.
* Instead of hard-coding Labels and Selector Labels, use a `helper` to pull them through
* Use the standard `helm create chart` generated helper utils
* Template the `config` in the Config Map
* Add `extraInitContainers` to the Deployment
* Template the `persistence.volumes` and `persistence.mounts`
* Use the Helm `nindent` standard instead of `indent`
* Add support for some Global values (`podAnnotations`, `podLabels`, `pullSecrets`)
* Template `podLabels` and `podAnnotations` values
* Pass `extraInitContainers` to Template helper
=> zenAptix upstream refactor contribution

README.md, charts/verdaccio/Chart.yaml, charts/verdaccio/templates/deployment.yaml, charts/verdaccio/templates/htpasswd-secret.yaml, charts/verdaccio/values.yaml
- Added support to have htpasswd credentails in helm values. So, a htpasswd file generated.
=> feat: Add htpasswd generator using helm.

README.md, charts/verdaccio/Chart.yaml, charts/verdaccio/templates/ingress.yaml, charts/verdaccio/values.yaml
* Remove `ingress.useExtensionsApi`
* Add `ingress.className`
* Auto-detect k8s version to figure out appropriate Ingress API Version
* Update Readme with missing ingress config
This adds support for `networking.k8s.io/v1` for Ingresses, added in
k8s `1.19` and required in `1.22`
=> feat: Ingress v1 API Version

charts/verdaccio/Chart.yaml, charts/verdaccio/templates/ingress.yaml
Currently, deployment fails for Kubernetes Clusters running on versions <1.18, as the old networking namespace haven't had the `pathType` field included. 
I added a check around the field for normal path's, just as it already was for extraPath's.
=> Added check to only apply pathType on k8s >= 1.18

README.md, charts/verdaccio/Chart.yaml, charts/verdaccio/templates/deployment.yaml, charts/verdaccio/values.yaml
Allows for injection of environment variables contained in an externally-defined secret.
Related issue: https://github.com/verdaccio/charts/issues/99
=> Feat: existing secret

.github/dependabot.yml
Dependabot [recently got support ](https://github.blog/changelog/2022-11-16-dependabot-version-updates-for-docker-image-tags-in-kubernetes-manifests/)for Docker Image version bumps in kubernetes manifests.
=> Feat: Dependabot Config

README.md
`helm install verdaccio/verdaccio`  will got error: 
```sh
Error: INSTALLATION FAILED: must either provide a name or specify --generate-name
```
I added the missing name for the chart release.
=> chore: fix install cmd error in README.md

README.md, charts/verdaccio/Chart.yaml, charts/verdaccio/values.yaml
Be aware of a new deprecation warning introduced here https://github.com/verdaccio/verdaccio/releases/tag/v5.22.1 this PR update the default Chart log configuration but still backward compatible, read release for more details.
=> feat: update image to v5.21.1

README.md, charts/verdaccio/Chart.yaml, charts/verdaccio/templates/deployment.yaml, charts/verdaccio/values.yaml
Support for setting deployment annotations via values. Useful for providing metadata values used in scripts or for informational purposes.
=> feat: Annotations to set on the deployment via values

charts/verdaccio/Chart.yaml, charts/verdaccio/templates/deployment.yaml, charts/verdaccio/values.yaml
I would like to be able to change the default `revisionHistoryLimit` which is by default 10 :
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
I don't need to be able to roll back 10 times, would much rather have the performance.
This is of course different from user to user, which is why I want to have it as a variable.
From source:
=> add revision history limit

README.md, charts/verdaccio/Chart.yaml, charts/verdaccio/templates/deployment.yaml, charts/verdaccio/values.yaml
https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/
=> feat: add topology spread constraints

charts/verdaccio/Chart.yaml, charts/verdaccio/values.yaml
Fix CrashLoopBackOff errror
```
warn --- config file  - /verdaccio/conf/config.yaml
warn --- Plugin successfully loaded: verdaccio-htpasswd
warn --- Plugin successfully loaded: verdaccio-audit
warn --- invalid address - http://0.0.0.0:tcp://10.230.80.202:4873, we expect a port (e.g. "4873"), host:port (e.g. "localhost:4873") or full url (e.g. "http://localhost:4873/")
```
=> Update default extraEnvVars

README.md, charts/verdaccio/Chart.yaml, charts/verdaccio/templates/deployment.yaml, charts/verdaccio/values.yaml
Remove the 'replicas' field from the helm template if set to null by user.
If you are using Keda to auto-scale your runner, it will modify the 'spec.replicas' of the deployment. That will cause a drift from the manifest known to ArgoCD. Therefore ArgoCD resync the resource. But then Keda retry to update it, and so on.....
By modifing the deployment template, we ensure that the replicas field is not present in the helm template if set to null by the user, and therefore not watch by ArgoCD. Note that by default, Kubernetes will set de 'spec.replicas' field to 1 if not present.
Do three helm template:
- One with replicaCount to 1
- One with replicaCount to 0
- One with replicaCount to null
=> remove(deployment): the 'replicas' field from the helm template if not used by user

README.md, charts/verdaccio/Chart.yaml, charts/verdaccio/templates/deployment.yaml, charts/verdaccio/templates/extra-manifests.yaml, charts/verdaccio/templates/service.yaml, charts/verdaccio/values.yaml
In order to add metrics thanks to the plugin https://github.com/freight-hub/verdaccio-openmetrics, we need to expose the ports.
- Add a `extraPorts` value, that contain a list of ports to add to the service and container.
- Add a `extraManifests` value, that contain a list of kubernetes manifests to deploy within the chart. This is very useful to, for example, add a ServiceMonitor so the service is scraped by prometheus.
- (fix) Add a default name (http) for the service port.
This is not a breaking change, as the new variables are a list with a default empty one and there is a range to iterate over them.
=> feat: allow adding extra ports and manifests

README.md, charts/verdaccio/Chart.yaml, charts/verdaccio/templates/pvc.yaml, charts/verdaccio/values.yaml
This commit makes it possible to add custom annotations to the PVC and introduces a new property that allows keeping the data volume on a Helm uninstall operation.
=> Allow keeping the data volume

README.md, charts/verdaccio/Chart.yaml, charts/verdaccio/templates/pvc.yaml, charts/verdaccio/templates/statefulset.yaml, charts/verdaccio/values.yaml
When using verdaccio as purely an edge cache, multiple deployment replicas require that the storage PV support ReadWriteMany. However, such PVs are not always available.
A StatefulSet can be used instead, where each replica will have it's own PV. This has the downside that initially the storage will be empty and may take time for them to get populated.
To be clear, Using StatefulSet is primarly useful for when verdaccio is an edge cache; Using it as a regular NPM registry (accepting uploads), would require additional step of syncing artifacts.
=> feat: Provide ability to create statefulset

README.md, charts/verdaccio/Chart.yaml, charts/verdaccio/templates/ingress.yaml, charts/verdaccio/values.yaml
Adds `ingress.labels` to values, allowing consumers to add custom labels to the ingress.
Our company use labels on ingresses and routes to set them up for traffic from specific domains.
=> feat: allow custom labels to ingress
