verdaccio/charts

.github/workflows/release.yml

https://github.com/helm/chart-releaser-action/releases/tag/v1.0.0-rc.2

Update chart-releaser-action@v1.0.0-rc.2 action

---

charts/verdaccio/Chart.yaml

I'm removing the previous list of maintainers, but obviously me 😋remains, but please, **feel free to amend this and ad yourself if you want to be in this list**.
I have no contact with `etiennetremel`, so if in any case, you read this and still want to be here, please no doubt to point it out and I'll restore it.

Maintainers update

---

charts/verdaccio/Chart.yaml

bump up to 0.7.6

---

charts/verdaccio/Chart.yaml

I'm not sure whether `name`  prop is correct

add Jhon Mike as maintainer

---

README.md

Update readme with new install steps

Update readme with new install steps

---

charts/verdaccio/Chart.yaml

This is the latest release in the v3 branch.

Bump Docker to v3.13.1

---

README.md
charts/verdaccio/Chart.yaml
charts/verdaccio/templates/deployment.yaml
charts/verdaccio/values.yaml

customConfigMap parameter implementation

---

charts/verdaccio/Chart.yaml

Update docker image to `v4.7.2`

feat: update docker to v4.7.2

---

README.md
charts/verdaccio/Chart.yaml
charts/verdaccio/templates/deployment.yaml
charts/verdaccio/values.yaml

I'm using a custom container in a private registry. This PR adds support for imagePullSecrets.

Support imagePullSecrets

---

.github/workflows/release.yml

update release action
according https://github.com/helm/chart-releaser-action/releases

chore:  update helm/chart-releaser-action

---

.github/workflows/release.yml

due this https://github.com/helm/chart-releaser-action/issues/61

chore: downgrade to releaser v1.0.0

---

charts/verdaccio/Chart.yaml
charts/verdaccio/values.yaml

It regular bum up and fix Snyk warning regarding outdated image

feat: bump up verdaccio@4.10.0

---

README.md
charts/verdaccio/Chart.yaml
charts/verdaccio/templates/deployment.yaml
charts/verdaccio/values.yaml

Adds the affinity value so we can assign pods with more options

feat: Add affinity value to deployment

---

README.md
charts/verdaccio/Chart.yaml
charts/verdaccio/values.yaml

Update image tag in chart.  It is actually 4.12.0
**PR Checklist**:

[verdaccio] Update image tag

---

README.md
charts/verdaccio/Chart.yaml

* I misjudged the changes I made and incorrectly bumped by minor instead
of major. This caused issues during upgrades
This (hopefully) fixes #55 
My apologies for the mistake :broken_heart:

Major version bump, fix #55

---

charts/verdaccio/Chart.yaml
charts/verdaccio/templates/NOTES.txt

Update NOTES.txt with correct label selectors
Fixes #58

Fix errors in NOTES.txt

---

README.md
charts/verdaccio/Chart.yaml
charts/verdaccio/values.yaml

- Update base image from v4 to v5
⚠️ ⚠️ ⚠️ Breaking changes, please read the document.
https://verdaccio.org/blog/2021/04/14/verdaccio-5-migration-guide

feat!: upgrade appVersion to 5.0.1

---

README.md
charts/verdaccio/Chart.yaml
charts/verdaccio/values.yaml

fix: update docker image to 5.0.4

---

README.md
charts/verdaccio/Chart.yaml
charts/verdaccio/values.yaml

New release https://github.com/verdaccio/verdaccio/discussions/2274

feat: update base to v5.1.0

---

.github/workflows/lint-test.yaml
README.md
charts/verdaccio/Chart.yaml
charts/verdaccio/values.yaml

- fix pipeline issues
- update base image to 5.1.1

update to base image 5.1.1

---

README.md
charts/verdaccio/Chart.yaml
charts/verdaccio/templates/deployment.yaml
charts/verdaccio/templates/htpasswd-secret.yaml
charts/verdaccio/values.yaml

bumping version **4.2.0**, regarding PR **69** 
@kav @pshanoop

checking array if empty to remove redundant flag

---

README.md
charts/verdaccio/Chart.yaml

feat: upgrade to 5.5.0

---

README.md
charts/verdaccio/Chart.yaml
charts/verdaccio/templates/deployment.yaml
charts/verdaccio/values.yaml

* Added the configuration options for all possible values of liveness
and readiness probes (initialDelaySeconds, periodSeconds,
timeoutSeconds, successThreshold, failureThreshold)

feat: Added configuration options for probes

---

README.md
charts/verdaccio/Chart.yaml
charts/verdaccio/values.yaml

Update Verdaccio from `5.5.0` to `5.15.3`
I believe this solves #102

Chore: Verdaccio `5.15.3`

---

README.md
charts/verdaccio/Chart.yaml
charts/verdaccio/values.yaml

Bump Verdaccio Chart AppVersion `5.15.3` -> `5.17.0`

Bump Chart AppVersion to `5.17.0`

---

README.md
charts/verdaccio/Chart.yaml
charts/verdaccio/values.yaml

feat: bump to v5.18.0

---

charts/verdaccio/Chart.yaml
charts/verdaccio/templates/configmap-nginx.yaml
charts/verdaccio/templates/deployment.yaml
charts/verdaccio/templates/service.yaml
charts/verdaccio/values.yaml

replacement for https://github.com/verdaccio/charts/pull/149

feature: add caching nginx

---

.github/workflows/lint-test.yaml
README.md
charts/verdaccio/Chart.yaml
charts/verdaccio/templates/deployment.yaml
charts/verdaccio/values.yaml

addresses #162 
This PR allows the consumer to specify and configure the deployment strategy, while keeping existing defaults.

feat: allow configurable deployment strategy
